# Generated by Django 4.2 on 2024-06-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_detailnote_recuperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailnote',
            name='note_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
