# Generated by Django 4.2 on 2024-06-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detailnote_note_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailnote',
            name='note_final',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
